### PR TITLE
fix：if play multiple video files aways catch error that use a widget …

### PR DESCRIPTION
**Pull request by zxhwyp**
fix：if play multiple video files aways catch error that use a widget that disposed

### CODE REVIEW

**Comment by rakesh4577** [comment]
@zxhwyp thank you for defecting the bug, hopefully, @vikram25897 will update it soon and btw I have tested your changes in listview, it is caching the video but not using the cache when we play again, let me know if I'm wrong.

**Comment by zxhwyp** [comment]
i do play video without net and  is fine, but i do not use list, play video  just in a page. and i think the code has no effect on video cache, so maybe we need track the event that why do not use cache

**Comment by rakesh4577** [comment]
hopefully, @vikram25897  will update us on this.

**Comment by rakesh4577** [comment]
@zxhwyp  hey, when I use this package in null safe flutter app with all the firebase services added it's not even caching a single video 😔 , I am so messed up, can you suggest something? but when I use this in my old simple page view app it's working fine, I am trying to find the bug for days but still no success.

**Pull request merged**
